
trigger:
- master
- mr/*

pr:
- master

resources:
  repositories:
    - repository: CImakeshift
      type: github
      name: mbeutel/CImakeshift
      endpoint: mbeutel

jobs:
- template: azure-pipelines/cmake.yml@CImakeshift
  parameters:
    vcpkgRef: f78f4440df86358575dea65e748a39fdad41eb85

    cmakeConfigArgs: '-DMAKESHIFT_BUILD_TESTS=ON'
    cmakeTestArgs: '--exclude-regex "cuda"' # do not run CUDA tests

    cmakeBuildConfigurations: [Debug, RelWithDebInfo]

    targets:

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: Clang
      cxxCompilerVersions: [VS2019, VS2022]
      platforms: [x86, x64]

    - os: Windows
      cxxCompiler: MSVC
      cxxCompilerVersions: [VS2022]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_7]
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DMAKESHIFT_BUILD_CUDA_TESTS=ON'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [10]
      platforms: [x64]

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [12]
      platforms: [x64]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer]
      tag: 'sanitize'

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [8]
      platforms: [x64]

    - os: Linux
      cxxCompiler: Clang
      cxxCompilerVersions: [14]
      platforms: [x64]
      cxxStandardLibraryDebugMode: true
      cxxSanitizers: [AddressSanitizer, UndefinedBehaviorSanitizer, ImplicitIntegerArithmeticValueChange]
      tag: 'sanitize'

    - os: Linux
      cxxCompiler: GCC
      cxxCompilerVersions: [11]
      cudaCompiler: NVCC
      cudaCompilerVersions: [11_7]
      platforms: [x64]
      cmakeConfigArgs: '<cmakeConfigArgs> -DMAKESHIFT_BUILD_CUDA_TESTS=ON'

    - os: MacOS
      cxxCompiler: GCC
      cxxCompilerVersions: [10, 12]
      platforms: [x64]

    - os: MacOS
      cxxCompiler: AppleClang
      cxxCompilerVersions: [13, 13_1_6]
      platforms: [x64]
